from crawler.analyzers.air_analyzer import AirAnalyzer
from crawler.analyzers.buy_queue import BuyQueueAnalyzer
from crawler.analyzers.cheap_rights_issue import CheapRightIssueAnalyzer
from crawler.analyzers.good_price_rights_issue import GoodPriceRightIssueAnalyzer
from crawler.analyzers.macd_cross import MACDCrossAnalyzer
from crawler.analyzers.new_comer_drop import NewComerDropAnalyzer
from crawler.analyzers.option_analyzer import OptionAnalyzer
from crawler.analyzers.volume_analyzer import VolumeAnalyzer
