# Generated by Django 3.0.3 on 2020-04-20 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('enable', models.BooleanField(default=True)),
                ('bazaar', models.IntegerField(choices=[(1, 'Boors'), (2, 'Faraboorse')], null=True)),
                ('bazaar_type', models.IntegerField(choices=[(1, 'Naghdi'), (2, 'Pure'), (3, 'Moshtaghe'), (4, 'Basic'), (7, 'Boorsekala')], null=True)),
                ('bazaar_group', models.IntegerField(null=True)),
                ('total_count', models.BigIntegerField(null=True)),
                ('base_volume', models.BigIntegerField(null=True)),
                ('option_strike_price', models.BigIntegerField(default=None, null=True)),
                ('option_strike_date', models.DateField(default=None, null=True)),
                ('eps', models.IntegerField(null=True)),
                ('last_update', models.DateTimeField(null=True)),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='crawler.ShareGroup')),
                ('option_base_share', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='crawler.Share')),
            ],
        ),
        migrations.CreateModel(
            name='ShareDailyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first', models.IntegerField()),
                ('close', models.IntegerField()),
                ('tomorrow', models.IntegerField()),
                ('yesterday', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('volume', models.BigIntegerField()),
                ('count', models.BigIntegerField()),
                ('value', models.BigIntegerField()),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crawler.Share')),
            ],
            options={
                'unique_together': {('share', 'date')},
            },
        ),
    ]
