# Generated by Django 2.1 on 2018-08-31 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('eps', models.IntegerField(null=True)),
                ('last_update', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first', models.IntegerField()),
                ('last', models.IntegerField()),
                ('close', models.IntegerField()),
                ('yesterday', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('volume', models.BigIntegerField()),
                ('count', models.BigIntegerField()),
                ('value', models.BigIntegerField()),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Share')),
            ],
        ),
    ]
