# Generated by Django 2.1 on 2018-09-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharehistory',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='sharehistory',
            unique_together={('share', 'date')},
        ),
    ]
