# Generated by Django 3.0.3 on 2020-03-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20200315_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='base_volume',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='bazaar',
            field=models.IntegerField(choices=[(1, 'Boors'), (2, 'Faraboorse')], null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='bazaar_group',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='bazaar_type',
            field=models.IntegerField(choices=[(1, 'Naghdi'), (2, 'Pure'), (3, 'Moshtaghe'), (4, 'Basic'), (7, 'Boorsekala')], null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='share',
            name='group',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='total_count',
            field=models.BigIntegerField(null=True),
        ),
    ]
