# Generated by Django 3.0.5 on 2020-05-11 15:15

from django.db import migrations

from django.db.models import JSONField


class Migration(migrations.Migration):
    dependencies = [
        ('crawler', '0002_auto_20200424_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='extra_data',
            field=JSONField(null=True),
        ),
    ]
