# Generated by Django 2.1 on 2018-09-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20180901_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='symbol',
            new_name='ticker',
        ),
        migrations.AlterField(
            model_name='sharehistory',
            name='date',
            field=models.DateField(),
        ),
    ]
