# Generated by Django 3.0.5 on 2020-05-18 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('crawler', '0003_share_extra_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedailyhistory',
            old_name='close',
            new_name='last',
        ),
    ]
