# Generated by Django 3.0.3 on 2020-03-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20200325_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='ticker',
            field=models.CharField(max_length=256),
        ),
    ]
