# Generated by Django 3.0.7 on 2020-06-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_auto_20200518_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedailyhistory',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
