# Generated by Django 3.0.7 on 2020-07-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_auto_20200623_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='ticker',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
