# Generated by Django 3.1 on 2020-08-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_auto_20200701_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='extra_data',
            field=models.JSONField(null=True),
        ),
    ]
