# Generated by Django 3.1 on 2020-08-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_auto_20200804_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='option_strike_date',
            new_name='strike_date',
        ),
    ]
