# Generated by Django 3.1.2 on 2020-10-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_auto_20200818_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='option_base_share',
            new_name='base_share',
        ),
    ]
