# Generated by Django 4.1.3 on 2022-11-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0012_auto_20201018_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedailyhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
