# Generated by Django 4.2 on 2023-11-12 16:39

from django.db import migrations, models


def insert_isin(apps, schema_editor):
    Share = apps.get_model("crawler", "Share")
    updated_shares: list[Share] = []
    for share in Share.objects.all():
        if share.extra_data:
            share.isin = share.extra_data['کد 12 رقمی نماد']
            updated_shares.append(share)

    Share.objects.bulk_update(updated_shares, ['isin'], batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        ('crawler', '0013_alter_sharedailyhistory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='isin',
            field=models.CharField(blank=False, null=True, db_index=True, max_length=256, unique=True),
        ),
        migrations.RunPython(insert_isin, reverse_code=lambda apps, schema_editor: None),
    ]
