# Generated by Django 5.2.7 on 2025-11-15 13:28

import django.db.models.deletion
from django.db import migrations, models

import crawler.models


class Migration(migrations.Migration):
    dependencies = [
        ('crawler', '0014_share_isin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('size', models.IntegerField()),
                ('commodity_id', models.IntegerField()),
                ('commodity_name', models.CharField(db_index=True, max_length=256)),
            ],
            bases=(models.Model, crawler.models.HistoryHandler),
        ),
        migrations.AlterUniqueTogether(
            name='sharedailyhistory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sharedailyhistory',
            name='share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='history', to='crawler.share'),
        ),
        migrations.AddField(
            model_name='sharedailyhistory',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='history', to='crawler.contract'),
        ),
        migrations.AddConstraint(
            model_name='sharedailyhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('share__isnull', False)), fields=('date', 'share'),
                                               name='daily_history_date_share_unique'),
        ),
        migrations.AddConstraint(
            model_name='sharedailyhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('contract__isnull', False)),
                                               fields=('date', 'contract'), name='daily_history_date_contract_unique'),
        ),
        migrations.AddConstraint(
            model_name='sharedailyhistory',
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(('contract__isnull', True), ('share__isnull', False)),
                                   models.Q(('contract__isnull', False), ('share__isnull', True)), _connector='OR'),
                name='daily_history_share_contract_exclusion'),
        ),
        migrations.RenameModel(
            old_name='ShareDailyHistory',
            new_name='DailyHistory',
        ),
    ]
