# Generated by Django 6.0 on 2025-12-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0015_contract_alter_sharedailyhistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='identity',
            field=models.JSONField(null=True),
        ),
    ]
